//
//  StockListInteractor.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StockListInteractorInput {
    func load(request: StockListRequest)
}

protocol StockListInteractorOutput {
    func present(response: StockListResponse)
}

class StockListInteractor: StockListInteractorInput {
    var repository: Repository!
    
    var output: StockListInteractorOutput!
    // MARK: - Business logic
    func load(request: StockListRequest) {
        self.repository.requestStockList(arr: request.symbolList)
        .startWithResult { [unowned self] result in
            if let value = result.value {
                self.output.present(response: StockListResponse(stockList: value))
            } else {
                // Error
            }            
        }
    }
}
