//
//  StockListPresenter.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StockListPresenterInput {
    func present(response: StockListResponse)
}

protocol StockListPresenterOutput: class {
    func display(viewModel: StockListViewModel)
}

class StockListPresenter: StockListPresenterInput {
    weak var output: StockListPresenterOutput!
    
    // MARK: - Presentation logic
    func present(response: StockListResponse) {
     
        var modelList = [StockViewModel]()
        for item in response.stockList {
            modelList.append(StockViewModel(stock: item))
        }
        
        self.output.display(viewModel: StockListViewModel(modelList: modelList))
    }
}
