//
//  StockChartInteractor.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StockChartInteractorInput {
    func load(request: StockChartRequest)
}

protocol StockChartInteractorOutput {
    func present(response: StockChartResponse)
}

class StockChartInteractor: StockChartInteractorInput {
    var output: StockChartInteractorOutput!
    // MARK: - Business logic
    
    func load(request: StockChartRequest) {
        let data = StockGenerator.instance.generateStock(stock: request.stock)        
        self.output.present(response: StockChartResponse(data: data))
    }
}
