//
//  StockChartPresenter.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StockChartPresenterInput {
    func present(response: StockChartResponse)
}

protocol StockChartPresenterOutput: class {
    func display(viewModel: StockChartViewModel)
}

class StockChartPresenter: StockChartPresenterInput {
    weak var output: StockChartPresenterOutput!
    
    // MARK: - Presentation logic
    func present(response: StockChartResponse) {
        var array = [DayStockViewModel]()
        for item in response.data {
            array.append(DayStockViewModel(stock: item))
        }
        self.output.display(viewModel: StockChartViewModel(contents: array))
    }    
}
