//
//  StockChartPresenter.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StockChartPresenterInput {
    
}

protocol StockChartPresenterOutput: class {
    
}

class StockChartPresenter: StockChartPresenterInput {
    weak var output: StockChartPresenterOutput!
    
    // MARK: - Presentation logic
    
    
}
