//
//  StockChartConfigurator.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension StockChartViewController: StockChartPresenterOutput {
    
}

extension StockChartInteractor: StockChartViewControllerOutput {
}

extension StockChartPresenter: StockChartInteractorOutput {
}

class StockChartConfigurator {
    // MARK: - Object lifecycle
    static let sharedInstance = StockChartConfigurator()
    private init() {}
    // MARK: - Configuration
    func configure(viewController: StockChartViewController) {
        let router = StockChartRouter()
        router.viewController = viewController
        
        let presenter = StockChartPresenter()
        presenter.output = viewController
        
        let interactor = StockChartInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
