//
//  StockChartViewController.swift
//  StockChart
//
//  Created by Le Thanh Hai on 6/24/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol StockChartViewControllerInput {
}

protocol StockChartViewControllerOutput {
    
}

class StockChartViewController: BaseViewController, StockChartViewControllerInput {
    var output: StockChartViewControllerOutput!
    var router: StockChartRouter!
    
    // MARK: - Object lifecycle
    override func initialize() {
        StockChartConfigurator.sharedInstance.configure(viewController: self)
    }
}
